dist: xenial
os: linux
cache:
    apt: true
    directories:
        - $HOME/.composer/cache

language: php

jobs:
    fast_finish: true
    include:
        - php: 5.6
          env: CS_FIXER=run
        - php: 7.0
        - php: 7.1
        - php: 7.2
        - php: 7.3
        - php: 7.4
        - php: nightly
    allow_failures:
        - php: nightly

before_script:
    - composer install --no-interaction -o --no-progress --prefer-dist

script:
    - mkdir -p build/logs
    - php ./bin/simple-phpunit -v --coverage-clover build/logs/clover.xml
    - if [ "$CS_FIXER" = "run" ]; then php bin/php-cs-fixer fix --verbose --dry-run ; fi;

after_script:
    - php ./bin/coveralls -v
