name: "CI"

on:
  pull_request:
  push:
    branches:
      - master

env:
  COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  phpunit:
    name: "PHP ${{ matrix.php }} / Symfony ${{ matrix.symfony }} / Flags ${{ matrix.flags }}"
    runs-on: "ubuntu-20.04"

    strategy:
      fail-fast: false
      matrix:
        php:
          - "7.4"
          - "8.0"
          - "8.1"
          - "8.2"
        symfony:
          - "4.*"
          - "5.*"
        flags:
          - "--prefer-dist"
          - "--prefer-dist --prefer-lowest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"
        with:
          fetch-depth: 2

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php }}"
          coverage: none
          tools: flex, pecl, composer:v2
          ini-values: "date.timezone=Europe/Paris"

      - name: "Install dependencies with Composer"
        env:
          SYMFONY_REQUIRE: "${{ matrix.symfony }}"
        uses: "ramsey/composer-install@v2"
        with:
          composer-options: "--optimize-autoloader ${{ matrix.flags }}"

      - name: "Run PHPUnit"
        run: "php vendor/bin/simple-phpunit -v"
